name: examplezoladark.tf
on: 
  push:
    branch: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.examplezoladark.tf
      uses: appleboy/ssh-action@master
      with:
        host: www2.examplezoladark.tf
        username: root
        key: ${{ secrets.TF_SECRET }}
        port: 22
        script: |
          cd /opt/www_examplezoladark_tf
          git log -1
          git pull
          bash build.sh
